export default {
    'about': 'Představení',
    'color': 'Barva',
    'email': 'E-mail',
    'document': 'Dokument',
    'phone': 'Telefonní číslo',
    'address': 'Adresa',
    'video': 'Volební spot',
    'web': 'Webové stránky',
    'link': 'Odkaz',
    'social': 'Socmedia',
    'wiki': 'Wiki',
    'logo': 'Logo',
    'motto': 'Slogan',
    'photo': 'Profilová fotka',
    'gallery': 'Fotka',
    'support': 'Podpora',
    'values': 'Hodnota',
    'pr': 'Tisková zpráva',
    'program': 'Program',
    'graphics': 'Volební materiál',
    'media': 'Média',
    'event': 'Událost',
    'note': 'Poznámka',
    'mfo': 'Pohlaví',
    'core': 'Registr',
    'answer': 'Odpověď',
    'priority': 'Priorita',
    'leader': 'Volební lídr',
    'govrole': 'Vládní kandidát',
    'garant': 'Garant',
    'mayor': 'Starosta',
    'coalition': 'Koalice',
    'population': 'Počet obyvatel',
    'gps': 'GPS',
    'datovka': 'Datová schránka',
    'ico': 'IČO',
    'psc': 'PSČ',
    'ruian': 'RÚIAN',
    'orp': 'Obec s rozšířenou působností',
    'candidate': 'Přidán kandidát',
    'party': 'Přidána strana'
}