export default [
				{name: 'CNN Prima News', source: 'https://cnn.iprima.cz/domaci'},
				{name: 'iDnes', source: 'https://www.idnes.cz/zpravy/domaci'},
				{name: 'Novinky', source: 'https://www.novinky.cz/sekce/domaci-13'},
				{name: 'Česká televize', source: 'https://ct24.ceskatelevize.cz/rubrika/domaci-5'},
				{name: 'Blesk', source: 'https://www.blesk.cz/zpravy/politika'},
				{name: 'Aktuálně', source: 'https://zpravy.aktualne.cz/domaci/'},
				{name: 'iRozhlas', source: 'https://www.irozhlas.cz/zpravy-domov'},
				{name: 'Deník', source: 'https://www.denik.cz/z_domova/'},
				{name: 'Deník N', source: 'https://denikn.cz/tag/snemovni-volby/'},
				{name: 'Parlamentní listy', source: 'https://www.parlamentnilisty.cz/'},
				{name: 'Deník Referendum', source: 'https://denikreferendum.cz/rubrika/domov'},
				{name: 'ČTK', source: 'https://www.ceskenoviny.cz/cr/'},
				{name: 'Praha IN', source: 'https://www.prahain.cz/'},
				{name: 'Seznam Zprávy', source: 'https://www.seznamzpravy.cz/sekce/volby-do-poslanecke-snemovny-242'},
				{name: 'Forum 24', source: 'https://www.forum24.cz/rubrika/domaci'},
				{name: 'INFO', source: 'https://www.info.cz/'},
				{name: 'TN.cz', source: 'https://tn.nova.cz/zpravodajstvi/tema/6790-domaci'},
				{name: 'Echo24', source: 'https://www.echo24.cz/'},
				{name: 'DVTV', source: 'https://www.dvtv.cz/screens/home'},
				{name: 'Hospodářky', source: 'https://hn.cz/'},
				{name: 'E15', source: 'https://www.e15.cz/'},
				{name: 'Respekt', source: 'https://www.respekt.cz/'},
				{name: 'Radiožurnál', source: 'https://radiozurnal.rozhlas.cz/'}
			]